import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { UserProvider } from "@/app/context/UserContext";
import { NotesProvider } from "./context/NotesContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notes",
  description: "Generated by Jainish",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <NotesProvider>{children}</NotesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
